config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments, only: [:new, :create]
  end
  root to: 'blogs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :description
  has_many :comments, dependent: :destroy

  broadcasts
  # broadcasts does the all following things.
  # after_create_commit -> {broadcast_append_to self}
  # after_update_commit -> {broadcast_replace_to self}
  # after_destory_commit -> {broadcast_remove_to self}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  has_rich_text :content

  broadcasts_to :blog

  # broadcasts_to does the all following things on blog.
  # after_create_commit -> {broadcast_append_to blog}
  # after_update_commit -> {broadcast_replace_to blog}
  # after_destory_commit -> {broadcast_remove_to blog}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog
  def new
    @comment = @blog.comments.new
  end

  def create
    @comment = @blog.comments.create(comment_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @blog }
    end
  end


  private

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.erb
<%= content_tag :div, id: dom_id(blog) do %>
  <h1><%= blog.title %></p>
  <p><%= blog.description %></p>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= turbo_frame_tag 'blog' do %>
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<%= turbo_stream_from @blog %>

<%= turbo_frame_tag 'blog' do %>
  <%= render @blog %>
  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%= link_to 'Back', blogs_path, 'data-turbo-frame': :_top %>
<% end %>

<div id="comments">
  <h2>Comments</h2>
  <%= render @blog.comments %>
</div>

<%#= link_to 'New comment', new_blog_comment_path(@blog) %>

<%= turbo_frame_tag 'new_comment', src: new_blog_comment_path(@blog), target: :_top %>

app/views/comments/_comment.html.erb
<%= content_tag :div, id: dom_id(comment) do %>
  <em>Someone said <%= time_ago_in_words(comment.created_at) %> ago</em>
  <p><%= comment.content %></p>
  <hr/>
<% end %>

app/views/comments/create_turbo_stream.erb
<%#= turbo_stream.append 'comments', @comment %>

app/views/comments/new.html.erb
<%= turbo_frame_tag 'new_comment' do %>
  <h2>New comment</h2>
  <%= form_with model: [@blog, @comment], data: { controller: 'reset_form', action: 'turbo:submit-end->reset_form#reset' } do |form| %>
    <div class="field">
      <%= form.rich_text_area :content %>
      <%= form.submit "Post", 'data-reset_form-target': 'button' %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppHotwire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <div class="container">
      <%= link_to "Home", root_path %>
      <%= yield %>
    </div>
  </body>
</html>